mutation updateApplicationStatus($isApproved: Boolean!, $applicationId: Int!, $isDenied: Boolean) {
  updateTenantApplicationStatus(input: {isApproved: $isApproved, applicationId: $applicationId, isDenied: $isDenied}) {
    success
  }
}