export default [
  {code: 'A0', name: 'Cape Cod'},
  {
    code: 'A1',
    name: 'Two Stories Detached',
  },
  {code: 'A2', name: 'One Story (Permanent Living Quarters)'},
  {code: 'A3', name: 'Large Suburban Residence'},
  {code: 'A4', name: 'City Residence'},
  {code: 'A5', name: 'Attached or Semi-Detached'},
  {code: 'A6', name: 'Summer Cottages/Mobile Homes/Trailers'},
  {code: 'A7', name: 'Mansion Type'},
  {code: 'A8', name: 'Bungalow Colony/Land Coop Owned'},
  {
    code: 'A9',
    name: 'Miscellaneous',
  },
  {code: 'B1', name: 'Brick'},
  {code: 'B2', name: 'Frame'},
  {code: 'B3', name: 'Converted (From One Family)'},
  {code: 'B9', name: 'Miscellaneous'},
  {code: 'C0', name: 'Three Families'},
  {code: 'C1', name: 'Over Six Families Without Stores'},
  {code: 'C2', name: 'Five to Six Families'},
  {code: 'C3', name: 'Four Families'},
  {code: 'C4', name: 'Old Law Tenements'},
  {code: 'C5', name: 'Converted Dwelling or Rooming House'},
  {code: 'C6', name: 'Cooperative (Other Than Condominiums)'},
  {code: 'C7', name: 'Over Six Families With Stores'},
  {code: 'C8', name: 'Co-op Conversion From Loft/Warehouse'},
  {code: 'C9', name: 'Garden Apartments/Mobile Home Park/Trailer Park'},
  {code: 'D0', name: 'Co-op Conversion From Loft/Warehouse'},
  {code: 'D1', name: 'Semi-fireproof'},
  {code: 'D2', name: 'Artists in Residence'},
  {code: 'D3', name: 'Fireproof'},
  {code: 'D4', name: 'Cooperatives'},
  {code: 'D5', name: 'Converted'},
  {code: 'D6', name: 'Fireproof - With Stores'},
  {code: 'D7', name: 'Semi-Fireproof With Stores'},
  {code: 'D8', name: 'Luxury Type'},
  {code: 'D9', name: 'Miscellaneous'},
];
