query GetManagementTeamByBuilding($building: Int!) {
  getManagementTeam(building: $building) {
    members {
      fullName
      picture
      userTitle
      pk
    }
    company {
      id
    }
    owner {
      id
    }
  }
}
