# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number()

    api_key = app_store_connect_api_key(
      key_id: "8WQN52927T",
      issuer_id: "84ab17f7-0d63-48a3-acd3-36ba00de7a6b",
      key_filepath: File.join(Dir.pwd,"./AuthKey_8WQN52927T.p8"),
      duration: 1200,
      in_house: true 
    )

    sync_code_signing(
      type: "appstore", 
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    )

    build_app(
      workspace: "PMClient.xcworkspace", 
      scheme: "PMClient",
      clean: true,
      export_method: "app-store",
    )

    upload_to_testflight(api_key: api_key)
  end

  lane :release do
    increment_build_number(xcodeproj: "PMClient.xcodeproj")

    build_app(
      workspace: "PMClient.xcworkspace", 
      scheme: "PMClient",
      clean: true,
      export_method: "app-store",
    )

    api_key = app_store_connect_api_key(
      key_id: "8WQN52927T",
      issuer_id: "84ab17f7-0d63-48a3-acd3-36ba00de7a6b",
      key_filepath: File.join(Dir.pwd,"./AuthKey_8WQN52927T.p8"),
      duration: 1200,
      in_house: true 
    )

    deliver(
        submit_for_review: true,
        automatic_release: true,
        force: true,
        skip_screenshots: true,
        skip_metadata: false,
        precheck_include_in_app_purchases: false,
        submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: true,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: true,
        content_rights_has_rights: false,
        content_rights_contains_third_party_content: false,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_uses_encryption: false,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: false,
        }
    )
    upload_to_app_store(api_key: api_key)
  end
end