query ProviderReviews($id: ID!) {
  serviceProvider(id: $id) {
    rank
    topReviews {
      edges {
        node {
          id
          rank
          text
          reviewer {
            id
            fullName
            picture
          }
        }
      }
    }
  }
}
