query ListTenants ($creator: Int){
  getTenantsByCreator(creatorId: $creator){
    edges{
      node{
        fullName
        firstName
        lastName
        id 
        picture
        pk
        
      }
    }
  }
}
