query ListMaintenanceRequests($status: Int, $after: String, $first: Int) {
  maintenanceRequests(after: $after, first: $first, status: $status) {
    pageInfo {
      endCursor
      hasNextPage
    }
    edges {
      node {
        id
        task {
          id
          title
          createdAt
        }
      }
    }
  }
}
