import { colors } from 'styles/theme';
import { typography } from 'styles/typography';

export const shadowedCard = {
  shadowRadius: 7,
  shadowColor: '#000',
  shadowOffset: { height: 3, width: 1 },
  elevation: 4,
  shadowOpacity: 0.7,
};

export const styles = {
  labelContainer: {
    backgroundColor: '#fff',
    height: 54,
    alignSelf: 'flex-end',
    width: '100%',
    zIndex: 10,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    borderRadius: 0,
    alignItems: 'center',
  },
  labelText: {
    status: null,
    color: '#335150',
    marginLeft: 18,
    fontSize: 18,
    fontWeight: 'bold',
  },
  background: {
    width: '120%',
    height: 108,
    margin: 0,
    marginBottom: 0,
    flexDirection: 'row',
    borderRadius: 18,
    marginLeft: -10,
    zIndex: 1,
    maxHeight: 120,
    position: 'relative',
  },
  container: {
    borderRadius: 10,
    marginTop: '10px',
    justifyContent: 'center',
    shadowRadius: 7,
    overflow: 'hidden',
    mx: 10,
    marginBottom: '3px',
    paddingBottom: 1,
    ...shadowedCard,
    shadowOpacity: 0.36,
  },
  header: {
    width: '100%',
    backgroundColor: colors['primary/50'],
  },
  mainBox: {
    backgroundColor: colors['primary/50'],
  },
  secHeadContainer: {
    flex: 0.2,
    justifyContent: 'center',
    height: '100%',
  },
  secHeadRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
  },
  secHeadButton: {
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#E7E9E9',
    borderRadius: 12,
  },
  secHeadButtonIcon: {
    width: 70,
    height: 70,
  },
  secHeadButtonText: {
    ...typography['buttons/large'],
    color: colors['gray scale/90'],
    lineHeight: 24,
    fontWeight: 'bold',
    textAlign: 'center',
    padding: 10,
    marginTop: 5,
    width: '80%',
  },
  listContainer: {
    flex: 1,
    backgroundColor: '#fff',
    marginTop: 90,
  },
  categoryItem: {
    marginHorizontal: 15,
    marginTop: 15,
    flexDirection: 'row',
    paddingVertical: 13,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors['gray scale/5'],
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryItemIcon: {
    width: 11,
    height: 11,
    position: 'absolute',
    top: -10,
    right: 0,
  },
  categoryItemText: {
    fontSize: 16,
    color: colors['gray scale/90'],
  },
  headerContainer: {
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  headerLeftButton: {
    borderColor: '#fff',
    borderWidth: 1,
    borderRadius: 8,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 75,
    paddingVertical: 6,
  },
  headerLeftButtonIcon: {
    width: 16,
    height: 16,
  },
  headerLeftButtonText: {
    marginLeft: 8,
    color: '#fff',
    fontSize: 14,
  },
  headerText: {
    color: '#fff',
    fontSize: 18,
  },
  emptyContainer: {
    width: 75,
  },
  backgroundImage: {
    resizeMode: 'cover',
    width: '100%',
    margin: 0,
    padding: 0,
  },
};
